# Changes are disabled.
coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        enabled: yes
        target: 100%
    changes: False

comment:
  layout: "header, diff, uncovered"
